### ISSUE TITLE
add @types

### ISSUE THREAD

**Issue by Succubussix** [sebakerckhof/faster-schema#10]
add @types

**Comment by Succubussix** [comment]
```
 dm.messages[dm.initialLanguage][type] 
  at FasterSchema.messageForError (/node_modules/faster-schema/dist/FasterSchema.js:323:49)
    at ValidationContext.keyErrorMessage (/node_modules/faster-schema/dist/ValidationContext.js:61:25)
    at Object.error_schema (/dist/schema/dictionary.js:96:23)
    at /dist/api/products.js:31:41

```

**Comment by Succubussix** [comment]
i cant use this.value at custom but when i follow the docks using {value} error above is poping

**Comment by Succubussix** [comment]
yay returning custom string without defining its message. .will cost an error..

and FasterSchema.messageBox.messages({
  en: {
    passwordMismatch(){ return 'Passwords do not match' },
  },
}); 

messageBox doesnt even exist

**Comment by sebakerckhof** [comment]
The messagebox thing is no longer valid indeed, forgot to update that part of the docs.
See: https://github.com/sebakerckhof/faster-schema#customizing-validation-messages for defining custom messages.

**Comment by sebakerckhof** [comment]
Readme got updated.

**Comment by sebakerckhof** [comment]
V1.0.1 will also not throw when you return an undefined error type (instead it will use the error type name as error message).

About the types: I have currently no plans on adding these due to time constraints, but PR's are welcomed.

**Comment by Succubussix** [comment]
thanks, for now, I just modified to simple schema types to make it work. I really don't have time too xD to gen.. also btw good module.

```

export interface ValidationContext extends FasterSchemaValidationContextStatic {
    addValidationErrors(errors: any): void;
    clean(...args: any[]): any;
    getErrorForKey(key: any, ...args: any[]): any;
    reset(): void;
    setValidationErrors(errors: any): void;
    validationErrors(): any;
}

interface CustomValidationContext {
    /** The name of the schema key (e.g., "addresses.0.street") */
    key: string;

    /** The generic name of the schema key (e.g., "addresses.$.street") */
    genericKey: string;

    /** The schema definition object. */
    definition: SchemaDefinition;

    /** Does the object being validated have this key set? */
    isSet: boolean;

    /** Value to validate */
    value: any;

    /** The Mongo operator for which we're doing validation. Might be null. */
    operator: any;
    validationContext: ValidationContext;

    /**
     * Use this method to get information about other fields. Pass a field name
     * (non-generic schema key) as the only argument. The return object will
     * have isSet, value, and operator properties for that field.
     */
    field(): any;
    /**
     * Use this method to get information about other fields that have the same
     * parent object. Works the same way as field(). This is helpful when you use
     * sub-schemas or when you're dealing with arrays of objects.
     */
    siblingField(): any;

    /**
     * Call this to add validation errors for any key. In general, you should use
     * this to add errors for other keys. To add an error for the current key,
     * return the error type string. If you do use this to add an error for the
     * current key, return false from your custom validation function.
     */
    addValidationErrors(errors: FasterSchemaValidationError): any;
}

interface SchemaDefinition {
    type: any;
    label?: string | (() => string);
    optional?: boolean | (() => boolean);
    min?: number | boolean | Date | (() => number | boolean | Date);
    max?: number | boolean | Date | (() => number | boolean | Date);
    minCount?: number | (() => number);
    maxCount?: number | (() => number);
    allowedValues?: any[] | (() => any[]);
    decimal?: boolean;
    exclusiveMax?: boolean;
    exclusiveMin?: boolean;
    regEx?: RegExp | RegExp[];
    /**
     * For custom validation function. If you use an arrow function the context
     * for "this" will not be available. Use "custom: function() { return
     * something(this.value); }" instead.
     */
    custom?: (data: CustomValidationContext) => undefined | string | FasterSchemaValidationError;
    blackbox?: boolean;
    autoValue?: () => any;
    defaultValue?: any;
    trim?: boolean;
}

interface CleanOption {
    filter?: boolean;
    autoConvert?: boolean;
    removeEmptyStrings?: boolean;
    trimStrings?: boolean;
    getAutoValues?: boolean;
    isModifier?: boolean;
    extendAutoValueContext?: boolean;
    removeNullsFromArrays?: boolean;
}

interface FasterSchemaOptions {
    check?: boolean;
    clean?: CleanOption;
    defaultLabel?: string;
    humanizeAutoLabels?: boolean;
    requiredByDefault?: boolean;
    tracker?: any;
}

interface FasterSchemaValidationError {
    type: string;
    [key: string]: number | string;
}

interface FasterSchemaStatic {
    new(
        schema: {
            [key: string]: SchemaDefinition
            | BooleanConstructor | StringConstructor | NumberConstructor | DateConstructor
            | ArrayConstructor
            | string | RegExp
            | FasterSchema
        } | any[],
        options?: FasterSchemaOptions
    ): FasterSchema;
    namedContext(name?: string): FasterSchemaValidationContextStatic;
    addValidator(validator: () => boolean): any;
    pick(...fields: string[]): FasterSchemaStatic;
    omit(...fields: string[]): FasterSchemaStatic;
    clean(doc: any, options?: CleanOption): any;
    schema(key: string): SchemaDefinition;
    schema(): SchemaDefinition[];
    getDefinition(key: string, propList?: any, functionContext?: any): any;
    keyIsInBlackBox(key: string): boolean;
    labels(labels: { [key: string]: string }): void;
    label(key: any): any;
    Integer: RegExp;
    messages(messages: any): any;
    setDefaultMessages(data: message): void;
    messageForError(type: any, key: any, def: any, value: any): string;
    allowsKey(key: any): string;
    newContext(): ValidationContext;
    objectKeys(keyPrefix: any): any[];
    validate(obj: any, options?: ValidationOption): void;
    validator(options?: ValidationOption): () => boolean;
    extendOptions(options: string[]): void;
    RegEx: {
        Email: RegExp;
        EmailWithTLD: RegExp;
        Domain: RegExp;
        WeakDomain: RegExp;
        IP: RegExp;
        IPv4: RegExp;
        IPv6: RegExp;
        Url: RegExp;
        Id: RegExp;
        ZipCode: RegExp;
        Phone: RegExp;
    };
    ErrorTypes: {
        REQUIRED: string,
        MIN_STRING: string,
        MAX_STRING: string,
        MIN_NUMBER: string,
        MAX_NUMBER: string,
        MIN_NUMBER_EXCLUSIVE: string,
        MAX_NUMBER_EXCLUSIVE: string,
        MIN_DATE: string,
        MAX_DATE: string,
        BAD_DATE: string,
        MIN_COUNT: string,
        MAX_COUNT: string,
        MUST_BE_INTEGER: string,
        VALUE_NOT_ALLOWED: string,
        EXPECTED_TYPE: string,
        FAILED_REGULAR_EXPRESSION: string,
        KEY_NOT_IN_SCHEMA: string
    };
}

interface ValidationOption {
    modifier?: boolean;
    upsert?: boolean;
    clean?: boolean;
    filter?: boolean;
    upsertextendedCustomContext?: boolean;
    keys?: string[];
}

interface FasterSchemaValidationContextStaticKeys {
    name: string;
    type: string;
    value?: any;
}

interface FasterSchemaError {
    name: string;
    type: string;
}

interface message {
    messages: {
        [k: string]: {
            [k: string]: () => string
        }
    }
}

interface FasterSchemaValidationContextStatic {
    validate(obj: any, options?: ValidationOption): boolean;
    validateOne(doc: any, keyName: string, options?: ValidationOption): boolean;
    resetValidation(): void;
    isValid(): boolean;
    invalidKeys(): FasterSchemaValidationContextStaticKeys[];
    addInvalidKeys(errors: FasterSchemaError[]): void;
    keyIsInvalid(name: any): boolean;
    keyErrorMessage(name: any): string;
    getErrorObject(): any;
}


export const FasterSchema: FasterSchemaStatic;
export const FasterSchemaValidationContext: FasterSchemaValidationContextStatic;


export interface FasterSchema extends FasterSchemaStatic {
    debug: boolean;
    /** Validate a data object. Options: {keys: []} to limit */
    validate(obj: any, options?: ValidationOption): void;
    addValidator(validator: () => boolean): any;
    messages(messages: any): void;
}


export default FasterSchema;

```
