### ISSUE TITLE
benchmark? 

### ISSUE THREAD

**Issue by Succubussix** [sebakerckhof/faster-schema#9]

**Comment by Succubussix** [comment]
```
/schema-comparison/node_modules/simpl-schema/dist/SimpleSchema.js:514
        if (!this._schema.hasOwnProperty(parentFieldName)) throw new Error(`"${fieldName}" is in the schema but "${parentFieldName}" is not`);
                                                           ^

Error: "states.$" is in the schema but "states" is not
    at /root/proj/bench/schema-comparison/node_modules/simpl-schema/dist/SimpleSchema.js:514:66
    at Array.forEach (<anonymous>)
    at SimpleSchema.extend (/root/proj/bench/schema-comparison/node_modules/simpl-schema/dist/SimpleSchema.js:510:22)
    at /root/proj/bench/schema-comparison/simple-schema.js:20:92
    at Array.reduce (<anonymous>)
    at new SimpleSchema (/root/proj/bench/schema-comparison/simple-schema.js:20:19)
    at Object.<anonymous> (/root/proj/bench/schema-comparison/simple-schema.js:998:33)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
```

**Comment by Succubussix** [comment]
reopening there was an error

**Comment by Succubussix** [comment]
```
SIMPLE SCHEMA
start validate
validate: 1029.163ms
end validate
start clean
clean: 4043.609ms
end clean
FASTER SCHEMA
start validate
validate: 66.332ms
end validate
start clean
clean: 44.995ms
end clean
SUPERSTRUCT
start validate
validate: 29.931ms
end validate
```

nvm you just forgot one type there at 1024 ...
